version: '3.8'

services:
  app:
    container_name: fastapi
    build: ./app
    volumes:
      - ./app:/usr/src/app   
    ports:
      - 8000:8000
    networks:
      - main

  web:
    container_name: nuxt
    build: ./web
    depends_on:
      - app
    volumes:
      - ./web/:/usr/src/web
      - /usr/src/web/node_modules
    ports:
      - 8080:8080
    networks:
      - main

  nginx:
    container_name: nginx 
    build: ./nginx
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - main

networks:
  main:
    driver: bridge


# volumes: {}